In [1]:
 import numpy as np
 # Create a rank 1 array
 a = np.array([0, 1, 2])
print(type(a))
 # this will print(the dimension of the array
 print(a.shape)
 print(a[0])
 print(a[1])
 print(a[2])
 # Change an element of the array
 a[0] = 5
 print(a)

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [2]:
 # Create a rank 2 array
 b = np.array([[0,1,2],[3,4,5]])
 print(b.shape)
 print(b)
 print(b[0, 0], b[0, 1], b[1, 0])
 (2
 , 
3)


(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


(2, 3)

In [3]:
 # Create a 3x3 array of all zeros
 a = np.zeros((3,3))
 a



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
 # Create a 2x2 array of all ones
 b = np.ones((2,2))
 b

array([[1., 1.],
       [1., 1.]])

In [5]:
 c = np.full((3,3), 7)                     # Create a 3x3 constant array


In [6]:
c

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [7]:

 d = np.random.random((3,3))                                      # Create a 3x3 array filled with random values
 d

array([[4.87842892e-01, 9.98014025e-01, 8.44548718e-01],
       [4.48119830e-01, 1.00463003e-01, 3.05776617e-01],
       [5.30185815e-02, 8.44849662e-01, 4.79188444e-04]])

In [8]:

 e = np.eye(3)                                            # note mix of tuple and lists
 h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
 h

 e


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:

 f = np.array([2, 3, 1, 0])                      # convert list to array

 f

array([2, 3, 1, 0])

In [10]:
 g = np.arange(20)
 g                                             # arange() will create arrays with regularly incrementing value


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
                                                          
 h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])                 # note mix of tuple and list
 h

array([[0.+0.j, 1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j, 2.+0.j]])

In [12]:
 i = np.arange(1, 8, dtype=float)
i                                                       # create an array of range with float data type

array([1., 2., 3., 4., 5., 6., 7.])

In [13]:
 # linspace() will create arrays with a specified number of items which are
 # spaced equally between the specified beginning and end values
 j = np.linspace(2., 4., 5)
 j


array([2. , 2.5, 3. , 3.5, 4. ])

In [14]:
 # indices() will create a set of arrays stacked as a one-higher
 # dimensioned array, one per dimension with each representing variation
 # in that dimension
 k = np.indices((2,2))
 k
 

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [15]:
 # Let numpy choose the datatype
 x = np.array([0, 1])
 y = np.array([2.0, 3.0])
 # Force a particular datatype
 z = np.array([5, 6], dtype=np.int64)
 print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [16]:
 x = np.zeros((3, 3), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])
 print("x['a'].shape: ", x['a'].shape)
 print("x['a'].dtype: ", x['a'].dtype)
 print("x['b'].shape: ", x['b'].shape)
 print("x['b'].dtype: ", x['b'].dtype)

x['a'].shape:  (3, 3)
x['a'].dtype:  int32
x['b'].shape:  (3, 3, 3, 3)
x['b'].dtype:  float64


In [17]:
 x = np.array([5, 6, 7, 8, 9])
 x[1:7:2]


array([6, 8])

In [18]:
print(x[-2:5])
print(x[-1:1:-1])

[8 9]
[9 8 7]


In [19]:
 x[4:]

array([9])

In [20]:
 y = np.array([[[1], [2], [3]],
 [[4], [5], [6]]])
 print("Shape of y: ", y.shape)
 y[1:3]


Shape of y:  (2, 3, 1)


array([[[4],
        [5],
        [6]]])

In [21]:
 x[...,0]


array(5)

In [22]:
 a = np.array([[5, 6, 7, 8],
 [1, 2, 3, 4],
 [9, 10, 11, 12]])
 print("Array a:", a)




Array a: [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]


In [23]:
 b = a[:2, 1:3]
 print("Array b:\n", b)

Array b:
 [[6 7]
 [2 3]]


In [24]:
 print(a[0, 1])
 b[0, 0] = 77
 print(a[0, 1])


6
77


In [25]:
 row_r1 = a[1, :]   # Rank 1 view of the second row of a
 row_r2 = a[1:2, :] # Rank 2 view of the second row of a
 print(row_r1, row_r1.shape)  # Prints "[1 2 3 4] (4,)"
 print(row_r2, row_r2.shape)  # Prints "[[1 2 3 4]] (1, 4)"


[1 2 3 4] (4,)
[[1 2 3 4]] (1, 4)


In [26]:
 # Accessing columns of an array
 col_r1 = a[:, 1]    
# Rank 1 view of the second column
 col_r2 = a[:, 1:2]  # Rank 2 view of the second column
 print(col_r1, col_r1.shape)  # Prints "[6 2 10] (3,)"
 print(col_r2, col_r2.shape)  # Prints "[[6] [2] [10]] (3, 1)"


[77  2 10] (3,)
[[77]
 [ 2]
 [10]] (3, 1)


In [27]:
 # An example of integer array indexing.
 # The returned array will have shape (2,) and
 print(a[[0, 1], [0, 1]])
 # The above example of integer array indexing is equivalent to this:
 print(np.array([a[0, 0], a[1, 1]]))


[5 2]
[5 2]


In [28]:
 # When using integer array indexing, you can reuse the same element from th
 print(a[[0, 0], [1, 1]])


[77 77]


In [29]:
 # Equivalent to the previous integer array indexing example
 print(np.array([a[0, 1], a[0, 1]]))


[77 77]


In [30]:

 a = np.array([[1, 2], [3, 4], [5, 6]])                # Boolean array indexing: Useful to pick elements from an array that satisfy


In [31]:
 # Find the elements of a that are bigger than 2
 print(a > 2)

[[False False]
 [ True  True]
 [ True  True]]


In [32]:
 # Get the actual values
 print(a[a > 2])


[3 4 5 6]


In [33]:

 x = np.array([[1, 2], [3, 4], [5, 6]])
 y = np.array([[7, 8], [9, 10], [11, 12]])              # Element-wise operations


In [34]:
 # Elementwise sum; both produce the array
 print(x + y)
 print(np.add(x, y))



[[ 8 10]
 [12 14]
 [16 18]]
[[ 8 10]
 [12 14]
 [16 18]]


In [35]:
 # Elementwise difference; both produce the array
 print(x - y)
 print(np.subtract(x, y))


[[-6 -6]
 [-6 -6]
 [-6 -6]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]


In [36]:
 # Elementwise product; both produce the array
 print(x * y)
 print(np.multiply(x, y))


[[ 7 16]
 [27 40]
 [55 72]]
[[ 7 16]
 [27 40]
 [55 72]]


In [37]:
 # Elementwise division; both produce the array
 print(x / y)
 print(np.divide(x, y))


[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]
[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]


In [38]:
 # Elementwise square root; produces the array
 print(np.sqrt(x))


[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [39]:
 # Dot product examples
 x = np.array([[1, 2], [3, 4]])
 y = np.array([[5, 6], [7, 8]])
 a_vec = np.array([9, 10])
 b_vec = np.array([11, 12])


In [40]:
 # Inner product of vectors
 print(a_vec.dot(b_vec))
 print(np.dot(a_vec, b_vec))


219
219


In [41]:
 # Matrix / vector product
 print(x.dot(a_vec))
 print(np.dot(x, a_vec))


[29 67]
[29 67]


In [42]:
 # Matrix / matrix product
 print(x.dot(y))
 print(np.dot(x, y))


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [43]:
 # Sum function
 x = np.array([[1, 2], [3, 4]])


In [44]:
 # Compute sum of all elements
 print(np.sum(x))


10


In [45]:
 # Compute sum of each column
 print(np.sum(x, axis=0))


[4 6]


In [46]:
 # Compute sum of each row
 print(np.sum(x, axis=1))
 


[3 7]


In [47]:
 # Transpose
 x = np.array([[1, 2], [3, 4]])
 print(x)
 print(x.T)


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [48]:
 # Note that taking the transpose of a rank 1 array does nothing
 v = np.array([1, 2, 3])
 print(v)
 print(v.T)


[1 2 3]
[1 2 3]


In [49]:
 # Broadcasting
 # Adding a vector to each row of a matrix
 a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 v = np.array([1, 0, 1])


In [50]:
 # Add the vector v to each row of the matrix a with an explicit loop
 b = np.empty_like(a)
 for i in range(3):
    b[i, :] = a[i, :] + v
 print(b)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [51]:
 # Stack 3 copies of v on top of each other
 # Using np.tile to create a repeated matrix
 vv = np.tile(v, (3, 1))
 print(vv)


[[1 0 1]
 [1 0 1]
 [1 0 1]]


In [52]:
 # Add a and vv elementwise
 b = a + vv
 print(b)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [53]:
 a = np.array([[1,2,3], [4,5,6], [7,8,9]])
 v = np.array([1, 0, 1])
 # Add v to each row of a using broadcasting
 b = a + v
 print(b)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [54]:
 # Applications of broadcasting
 # Compute outer product of vectors
 v = np.array([1, 2, 3])  # shape (3,)
 w = np.array([4, 5])     
# shape (2,)
 # Reshape v to (3,1) and broadcast against w to get (3,2)
 print(np.reshape(v, (3, 1)) * w)


[[ 4  5]
 [ 8 10]
 [12 15]]


In [55]:
 # Add a vector to each row of a matrix
 x = np.array([[1, 2, 3], [4, 5, 6]])
 print(x + v)


[[2 4 6]
 [5 7 9]]


In [56]:
 # Add a vector to each column of a matrix
 # Using transpose and broadcasting
 print((x.T + w).T)
 # Alternative: reshape w to (2,1)
 print(x + np.reshape(w, (2, 1)))


[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]


In [57]:

 print(x * 2)                      # Multiply a matrix by a constant

                    



[[ 2  4  6]
 [ 8 10 12]]


In [58]:
 import pandas as pd


In [59]:
 # creating a series by passing a list of values, and a custom index label.
 # Note that the labeled index reference for each row and it can have duplic
s = pd.Series([1,2,3,np.nan,5,6], index=['A','B','C','D','E','F'])
 print(s)



A    1.0
B    2.0
C    3.0
D    NaN
E    5.0
F    6.0
dtype: float64


In [60]:
 data = {'Gender': ['F', 'M', 'M'],'Emp_ID': ['E01', 'E02',
 'E03'], 'Age': [25, 27, 25]}
 # We want the order the columns, so lets specify in columns parameter
 df = pd.DataFrame(data, columns=['Emp_ID','Gender', 'Age'])
 print(df)

  Emp_ID Gender  Age
0    E01      F   25
1    E02      M   27
2    E03      M   25


In [62]:
 # Reading
df=pd.read_csv('mtcars.csv') # from csv
df=pd.read_csv('mtcars.txt', sep='\t') # from text file
df=pd.read_excel('mtcars.xlsx',sheet_name = 'Sheet1') # from Excel
 # reading from multiple sheets of same Excel into different dataframes
xlsx = pd.ExcelFile('mtcars.xlsx')
sheet1_df = pd.read_excel(xlsx, 'Sheet1')
#sheet2_df = pd.read_excel(xlsx, 'Sheet2')

In [65]:
# index = False parameter will not write the index values, default is True
df.to_csv('mtcars_new.csv', index=False)
df.to_csv('mtcars_new.txt', sep='\t', index=False)
df.to_excel('mtcars_new.xlsx',sheet_name='Sheet1', index = False)


In [76]:
df = pd.read_csv("https://raw.githubusercontent.com/lovnishverma/datasets/refs/heads/main/iris_default.csv")

In [77]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [78]:
df.cov()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           0.685694         -0.042434           1.274315   
sepal width (cm)           -0.042434          0.189979          -0.329656   
petal length (cm)           1.274315         -0.329656           3.116278   
petal width (cm)            0.516271         -0.121639           1.295609   

                   petal width (cm)  
sepal length (cm)          0.516271  
sepal width (cm)          -0.121639  
petal length (cm)          1.295609  
petal width (cm)           0.581006

In [79]:
df.corr()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000

In [82]:
 data = {
 'emp_id': ['1', '2', '3', '4', '5'],
 'first_name': ['Jason', 'Andy', 'Allen', 'Alice', 'Amy'],
 'last_name': ['Larkin', 'Jacob', 'A', 'AA', 'Jackson']}


In [83]:
 df_1 = pd.DataFrame(data, columns = ['emp_id', 'first_name', 'last_name'])


In [84]:
 data = {
 'emp_id': ['4', '5', '6', '7'],
 'first_name': ['Brian', 'Shize', 'Kim', 'Jose'],
 'last_name': ['Alexander', 'Suma', 'Mike', 'G']}

In [85]:
 df_2 = pd.DataFrame(data, columns = ['emp_id', 'first_name', 'last_name'])


In [86]:
 df = pd.concat([df_1, df_2])
 print(df)


  emp_id first_name  last_name
0      1      Jason     Larkin
1      2       Andy      Jacob
2      3      Allen          A
3      4      Alice         AA
4      5        Amy    Jackson
0      4      Brian  Alexander
1      5      Shize       Suma
2      6        Kim       Mike
3      7       Jose          G


In [87]:
 # Join the two dataframes along columns
 pd.concat([df_1, df_2], axis=1)
 

emp_id first_name last_name emp_id first_name  last_name
0      1      Jason    Larkin      4      Brian  Alexander
1      2       Andy     Jacob      5      Shize       Suma
2      3      Allen         A      6        Kim       Mike
3      4      Alice        AA      7       Jose          G
4      5        Amy   Jackson    NaN        NaN        NaN

In [88]:
 # Merge two dataframes based on the emp_id value
 # in this case only the emp_id's present in both table will be joined
 pd.merge(df_1, df_2, on='emp_id')


emp_id first_name_x last_name_x first_name_y last_name_y
0      4        Alice          AA        Brian   Alexander
1      5          Amy     Jackson        Shize        Suma

In [89]:
 # Left join
 print(pd.merge(df_1, df_2, on='emp_id', how='left'))


  emp_id first_name_x last_name_x first_name_y last_name_y
0      1        Jason      Larkin          NaN         NaN
1      2         Andy       Jacob          NaN         NaN
2      3        Allen           A          NaN         NaN
3      4        Alice          AA        Brian   Alexander
4      5          Amy     Jackson        Shize        Suma


In [95]:
print(pd.merge(df_1, df_2, on='emp_id', how='left', suffixes=('_left', '_right')))




  emp_id first_name_left last_name_left first_name_right last_name_right
0      1           Jason         Larkin              NaN             NaN
1      2            Andy          Jacob              NaN             NaN
2      3           Allen              A              NaN             NaN
3      4           Alice             AA            Brian       Alexander
4      5             Amy        Jackson            Shize            Suma


In [96]:
# Right join
pd.merge(df_1, df_2, on='emp_id', how='right')

emp_id first_name_x last_name_x first_name_y last_name_y
0      4        Alice          AA        Brian   Alexander
1      5          Amy     Jackson        Shize        Suma
2      6          NaN         NaN          Kim        Mike
3      7          NaN         NaN         Jose           G

In [97]:
# Inner Join
pd.merge(df_1, df_2, on='emp_id', how='inner')

emp_id first_name_x last_name_x first_name_y last_name_y
0      4        Alice          AA        Brian   Alexander
1      5          Amy     Jackson        Shize        Suma

In [98]:
pd.merge(df_1, df_2, on='emp_id', how='outer')

emp_id first_name_x last_name_x first_name_y last_name_y
0      1        Jason      Larkin          NaN         NaN
1      2         Andy       Jacob          NaN         NaN
2      3        Allen           A          NaN         NaN
3      4        Alice          AA        Brian   Alexander
4      5          Amy     Jackson        Shize        Suma
5      6          NaN         NaN          Kim        Mike
6      7          NaN         NaN         Jose           G

In [99]:
# Create the DataFrame
df = pd.DataFrame({
    'Name': ['jack', 'jane', 'jack', 'jane', 'jack', 'jane', 'jack', 'jane'],
    'State': ['SFO', 'SFO', 'NYK', 'CA', 'NYK', 'NYK', 'SFO', 'CA'],
    'Grade': ['A', 'A', 'B', 'A', 'C', 'B', 'C', 'A'],
    'Age': np.random.uniform(24, 50, size=8),
    'Salary': np.random.uniform(3000, 5000, size=8)
})

In [100]:
# Display the DataFrame
print(df)

   Name State Grade        Age       Salary
0  jack   SFO     A  34.293629  3596.152985
1  jane   SFO     A  38.773157  3184.598113
2  jack   NYK     B  47.839425  4148.563637
3  jane    CA     A  45.322859  3483.898254
4  jack   NYK     C  48.848299  3984.245494
5  jane   NYK     B  30.052166  4055.593090
6  jack   SFO     C  40.312542  3301.753821
7  jane    CA     A  46.255806  3549.560174


In [101]:
# Find max age and salary by Name / State
# with groupby, we can use all aggregate functions such as min, max, mean, count, cumsum
df.groupby(['Name','State']).max()

Grade        Age       Salary
Name State                              
jack NYK       C  48.848299  4148.563637
     SFO       C  40.312542  3596.152985
jane CA        A  46.255806  3549.560174
     NYK       B  30.052166  4055.593090
     SFO       A  38.773157  3184.598113

In [102]:
# by state and name find mean age for each grade
pd.pivot_table(df, values='Age', index=['State', 'Name'], columns=['Grade'])

Grade               A          B          C
State Name                                 
CA    jane  45.789332        NaN        NaN
NYK   jack        NaN  47.839425  48.848299
      jane        NaN  30.052166        NaN
SFO   jack  34.293629        NaN  40.312542
      jane  38.773157        NaN        NaN